"""Auth 模块的常量定义"""

from enum import Enum


class ErrorCode(str, Enum):
    """Auth 模块错误代码"""

    # 认证相关错误
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # 用户相关错误
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    USERNAME_ALREADY_TAKEN = "USERNAME_ALREADY_TAKEN"

    # 权限相关错误
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    FORBIDDEN = "FORBIDDEN"

    # 验证相关错误
    INVALID_PASSWORD = "INVALID_PASSWORD"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_USERNAME = "INVALID_USERNAME"


class AuthConstants:
    """Auth 模块常量"""

    # Token 相关
    ACCESS_TOKEN_EXPIRE_MINUTES = 30
    REFRESH_TOKEN_EXPIRE_DAYS = 7

    # 密码相关
    MIN_PASSWORD_LENGTH = 8
    MAX_PASSWORD_LENGTH = 128

    # 用户名相关
    MIN_USERNAME_LENGTH = 3
    MAX_USERNAME_LENGTH = 20

    # 邮箱相关
    MAX_EMAIL_LENGTH = 100

    # 分页相关
    DEFAULT_PAGE_SIZE = 10
    MAX_PAGE_SIZE = 100
